### ISSUE TITLE
Robot Config Step 1 documentation has merge conflict artefacts in it

### ISSUE THREAD

**Issue by UserC2** [Autodesk/synthesis#1052]
**Describe the bug**
<img width="500" src="https://github.com/user-attachments/assets/06a5af54-fbf2-407a-9113-5c9aef803b21">
The text "<<<<<<< Updated Upstream" and "Stashed changes" appears on the first page of [Robot Config](https://synthesis.autodesk.com/codelab/ConfigModeCodelab/#0) documentation.

**To Reproduce**
See https://synthesis.autodesk.com/codelab/ConfigModeCodelab/#0

**Comment by HunterBarclay** [comment]
The tutorials are being rewritten in a couple weeks. Thank you for the report, though!
