### ISSUE TITLE
Trajectory Setting with Robot Reference Axis Skewed

### ISSUE THREAD

**Issue by perdlespedales** [Autodesk/synthesis#217]
If a Robot is defined with its axes so that it will be placed on its side when being added to the field, the release trajectory setting axes will also be skewed, making it impossible to properly set the trajectory. See attached screen capture.
Running Synthesis V4.2.0.1
![releasetrajectorysettingissue](https://user-images.githubusercontent.com/1322196/44302961-0beacf00-a302-11e8-908e-01573d71730b.jpg)

**Comment by HiceS** [comment]
Thanks for reporting this, I'll have someone look at fixing at asap.

**Comment by perdlespedales** [comment]
Hi! Issue finally resolved after I re-exported my robot's model using the V2.4.0.1 Inventor Robot Exporter add-in.
