### ISSUE TITLE
Joystick 4 constantly being pressed down, even when no controller is even connected 

### ISSUE THREAD

**Issue by yamaan93** [Autodesk/synthesis#259]
When trying to map joysticks and buttons from a controller, "joystick 4" is always registering, and overriding all over button presses, making it impossible to use. I thought this was a problem with the controller, but after restarting the app with dead zones on all the sticks so that no input should be read I found that the application itself thinks that "joystick 4" is always being held down, even with no controller connected. this has rendered the application useless if I can't map controller buttons.

**Comment by HiceS** [comment]
Thanks for posting this as an issue, we will have someone look into it. I myself haven't encountered this error but we will look into why it might be happening. 

Can you give us a little information on what kind of machine you are using? And what kind of joystick you last used if any.

**Comment by HiceS** [comment]
Okay thank you, that's very interesting. Seems like we may have a bug when dealing with Sony controllers. We do not have any of those controllers for testing under the presumption that they have similar drivers to Logitech. I'll let everyone know and see if we can get a fix out asap. 

Someone else has also emailed us about the exact same issue so I'm almost certain it's the PlayStation controller that we are having an issue with.

**Comment by HiceS** [comment]
I'll run to BestBuy soon and see what I can get to test with.

**Comment by yamaan93** [comment]
thank you so much,

**Comment by HiceS** [comment]
Hey Sorry for getting back to you so late, we have confirmed that it is an issue with the ps4 controller and the library we use to store values into our control scheme. This is a priority issue that will be fixed in the upcoming patch.

**Comment by yamaan93** [comment]
That's great, I was worried it was a problem with my controller, good to know

**Comment by yamaan93** [comment]
So the bug is still here, after the patch by the way

**Comment by HiceS** [comment]
Thank you for letting us know, last patch was mainly made to correct small field issues and drastically improve the code emulation interactions. Unfortunately the engine team didn't include many changes to support fixing the control mappings.

**Comment by KyroVibe** [comment]
Remedies have been put in place to address this issue. In the next release this should no longer be an issue. Only took 2 years
