### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by HiceS** [Autodesk/synthesis#260]
Hello everyone, we had a discussion about wether to keep our publicly known issues for the release in a forums post or on the git page. For now the git issue page has won.

## Version Number (4.2.0.1): [Release Link](https://github.com/Autodesk/synthesis/releases/tag/4.2.0.1)

- [x] Controller mappings disappear when changing fields
Fix: In release

- [x] When going through the Network Multiplayer Beta (LAN) wizard, the banner over the top says "Nework" instead of "Network". -insert name of reporter but I'm on mobile so check back later

- [x] Trying to setup our joysticks for tank drive (Attack 3 joysticks.), but it is not registering the joysticks properly. Both Joysticks read as Joystick 1.  

- [ ] PS4 Controllers are having issues with `Joystick4` [Issue posted](https://github.com/Autodesk/synthesis/issues/259)

- [x] Fusion 360 exporter buttons wont work 
Fix: right click on palette -> showdevtools (instantly fixes problem) [Issue posted](https://github.com/Autodesk/synthesis/issues/168)

- [x] Exporters export to %appdata%/Synthesis/Robots instead of %appdata%/Autodesk/Synthesis/Robots causeing issues for users.

-  [x] Support more than 8 CANIDs [issue posted](https://github.com/Autodesk/synthesis/issues/281)

-  [ ] Robot wheels not colliding with ground properly [issue posted](https://forums.autodesk.com/t5/bxd-synthesis-forum/robot-wheels-fall-through-the-ground/m-p/8703052)

-  [ ] Fusion 360 exporter won't start for some machines [issue posted](https://forums.autodesk.com/t5/bxd-synthesis-forum/synthesis-workspace-is-missing-from-fusion-360/td-p/8482820)

-  [ ] Fusion 360 exporter causes many crashes

**Comment by HiceS** [comment]
Controller mappings disappear fixed as of path 4.2.1.0

**Comment by HiceS** [comment]
Fusion 360 Problem seems to have been fixed by the fusion team.

**Comment by KiraCorbett** [comment]
Controls were updated and restructured quite a bit. It does not seem that Xbox controllers read as Joystick 1.
