### ISSUE TITLE
Typo on "Network"

### ISSUE THREAD

**Issue by cjdenio** [Autodesk/synthesis#279]
When going through the Network Multiplayer Beta (LAN) wizard, the banner over the top says "Nework" instead of "Network". It's not a huge issue, but something to maybe fix in the next release.

**Comment by HiceS** [comment]
Oh well that's not good, thank you for sending us this issue and we will get someone to fix it asap. Alternatively if you want to submit a push request with that specific change it might be beneficial.

**Comment by matthew17754** [comment]
Can confirm 'Nework' is now spelled correctly for the next patch. Thanks for your submission @cjdenio

**Comment by cjdenio** [comment]
Great thanks!
