### ISSUE TITLE
Got stuck when I went into quick reset

### ISSUE THREAD

**Issue by katiegrace** [Autodesk/synthesis#431]
I was in the Stronghold field with 188's 2016 robot. I pressed "quick reset" and then it won't let me return when I press the return button.

Also happens when I press "Change spawn point"

**Comment by perdlespedales** [comment]
Ran into the problem as well. None of the Reset functions work. The only way to exit the function is to terminate the task via the Windows Task Manager.

**Comment by KiraCorbett** [comment]
This issue has been confirmed and now merged. The fix will be available in our next patch update.
