### ISSUE TITLE
Could not find the selected robot!

### ISSUE THREAD

**Issue by perdlespedales** [Autodesk/synthesis#433]
In many occasions, when I launch Synthesis (Windows 10 - 64 bits version), the Robot Selection pop-up window opens with the following message: "Could not find the selected robot"
When selecting "Change Robot Directory", I am taken to the correct folder. By selecting the folder again, Synthesis becomes capable of finding the robot.

![image](https://user-images.githubusercontent.com/1322196/62907628-23f10500-bd42-11e9-8d11-cee98cffa533.png)

**Comment by KiraCorbett** [comment]
Thank you for pointing that out. I believe we are loading the incorrect "error screen." It should be possible to still load your robot although our user message is misleading.

**Comment by perdlespedales** [comment]
Hello Kira,

You are correct. I typically just click on the already highlighted folder
and Synthesis then proceeds to load the robot correctly.

Cheers,
Ronald



Le mar. 13 août 2019 à 12:55, Kira Corbett <notifications@github.com> a
écrit :

**Comment by Marcorse** [comment]
I have the same issue on the opening. I tried what Ronald just says, but it still doesn't work. Is there another way to fix this or to pass through the problem? I'll continue to look for any possibilities. 

Marc

**Comment by KiraCorbett** [comment]
Thank you. This issue has been updated and should be available in the next release.

**Comment by matthew17754** [comment]
#438 for reference

**Comment by yanmannqc** [comment]
I have the same issue with the latest build. And I can't use the samble or dozer robot at all.
