### ISSUE TITLE
Unable to use the gamepiece and scoring tabs

### ISSUE THREAD

**Issue by Atenshin** [Autodesk/synthesis#436]
The tabs are there, but it doesn't let me see what's in it or use it sometimes.

**Comment by KiraCorbett** [comment]
@Atenshin Are you experiencing this on the default grid? The default grid that your robot lands on when entering the simulator restricts access to those tabs. If you change to a FIRST field, most fields should allow for access on additional tabs if they have gamepieces.

**Comment by Atenshin** [comment]
Oh, yeah. It was in the grid. And I could access them in the actual fields.

**Comment by matthew17754** [comment]
@KiraCorbett Perhaps we should increase the time parameter in the `UserMessageManager.Dispatch()` to prevent confusion.
