### ISSUE TITLE
"User program not found"

### ISSUE THREAD

**Issue by eddy20001118** [Autodesk/synthesis#443]
When I selected my latest 2019 season code and clicked the "Run code" button, a message showed up saying "User program not found". The problem seems that QEMU was successfully booted but the code was not loaded. Does the v4.3.0 really support java code emulation?

**Comment by zero-frost** [comment]
There was an issue with package versioning in the latest build that caused errors with file uploading. This will be resolved in the next release.

**Comment by copernicium** [comment]
Thank you for reporting this issue. It has been fixed in release [v4.3.1](https://github.com/Autodesk/synthesis/releases/tag/v4.3.1).
