### ISSUE TITLE
Gamepiece selection can't be changed

### ISSUE THREAD

**Issue by Yipten** [Autodesk/synthesis#472]
**Describe the bug**
In the Gamepiece tab, the leftmost button shows a drop-down menu to select a different gamepiece. It seems like it should allow settings to be changed for the second gamepiece. However, selecting it doesn't appear to do anything. This makes it so the intake, release, trajectory, spawning, etc. for the second gamepiece can't be used. 

**To Reproduce**
1. Start Synthesis
2. Change to a field with two gamepieces such as 2019 Deep Space or 2017 Steamworks
3. Try changing the selected gamepiece in the Gamepiece tab

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 1903
 - Version: 4.3.1.1

**Comment by KyroVibe** [comment]
Hi @Yipten, thank you for reporting a bug.
It seems that this bug has already been fixed and will be in our patch release coming sometime after kickoff.
Sorry you had this issue but if you need this fixed you can follow our readme and build the unity project on our master branch in the directory "engine/"
