### ISSUE TITLE
No emulator download link?

### ISSUE THREAD

**Issue by ashah03** [Autodesk/synthesis#477]
**Description**
The emulation tab gives an "emulator not installed" error and there is no download/install link for the emulator on the website.

**Comment by matthew17754** [comment]
If you are running Windows, ensure that the code emulator box is checked when running the installation wizard. Emulation is only supported on the 64 bit installation of Synthesis.

Unfortunately code emulation is not yet supported on Linux & Macintosh operating systems. That is something we hope to release in the coming year.

Hope that clears things up.
