### ISSUE TITLE
Qemu not found on Arch

### ISSUE THREAD

**Issue by macmv** [Autodesk/synthesis#482]
**Describe the bug**
On Arch, I have installed the 'qemu' and 'qemu-arch-extra' packages, but Sythesis cannot find qemu. I don't know if there are more packages I need to install, but no combination of these will work.

**To Reproduce**
1. Install 4.3.2 through the latest github release for linux.
2. Install 'qemu' and 'qemu-arch-extra' through pacman.

**Expected behavior**
The emulator tab should show a Start button, not a Not Installed button.

**Desktop (please complete the following information):**
 - OS: Arch Linux 5.4.11-arch1-1
 - Sythesis Version 4.3.2

**Comment by matthew17754** [comment]
Hi @macmv 

Unfortunately there has been an update to the WPI Library API, and as a result, our emulation system is down at the moment. I do want to note that currently the only officially supported Linux distribution is Ubuntu.

I would recommend running emulation using the previous version of the WPI Library on a Windows machine. We apologize for the inconvenience.

**Comment by macmv** [comment]
Thank you for the quick response. Do you have any estimate of when the emulator will work again?

**Comment by matthew17754** [comment]
We are planning to do some restructuring to our current emulation system, due to the maintenance overhead of WPI constantly restructuring their API. I would expect to have the new system implemented by the end of this summer. Again, I'm really sorry about this.

**Comment by macmv** [comment]
Thanks for the information. I'm glad we could get this cleared up.
