### ISSUE TITLE
Fusion - Read Current Design

### ISSUE THREAD

**Issue by victoryforphil** [Autodesk/synthesis#506]
Load current design data and be ready to store it.

Data to load:
- Design name
- Design GUID
- Current user

**Comment by KiraCorbett** [comment]
![data](https://user-images.githubusercontent.com/16855850/85049924-2f734080-b14a-11ea-8c0d-0493cf88512f.JPG)
See branch [read-data](https://github.com/Autodesk/synthesis/tree/read-data) to be merged into `exporter-devel`.
