### ISSUE TITLE
Fusion - Read Component Tree

### ISSUE THREAD

**Issue by victoryforphil** [Autodesk/synthesis#507]
Write code to go through each component in the current design and read it's data, preparation for protocol buffer

**Comment by KiraCorbett** [comment]
![image](https://user-images.githubusercontent.com/16855850/85050316-bf18ef00-b14a-11ea-83b6-db01708e7584.png)
@victoryforphil @liamjwang If this looks okay I will clean up my code and merge into exporter-devel.
