### ISSUE TITLE
Implement Discord Rich Presence

### ISSUE THREAD

**Issue by matthew17754** [Autodesk/synthesis#610]
Add DRPC either at the engine level or as a module implementation.
|    DOD    | Done |    Asignees    | Branch | PR |
|-----------|------|----------------|-------|-----|
| Status    | ❌ | <assignee> | drpc | NA |

**Comment by Ahsoka** [comment]
@NickBurrell Could you link the relevant commit that closed this?  Thank you!

**Comment by KyroVibe** [comment]
Moved to [JIRA](https://jira.autodesk.com/browse/AARD-1445) for internal tracking
