### ISSUE TITLE
Make 'ESC' key exit current menu, not ask to exit Synthesis

### ISSUE THREAD

**Issue by TrevCan** [Autodesk/synthesis#677]
Most software uses the `esc` key to exit the current menu or process that is currently happening, but in Synthesis it will always ask to exit the program. It would be nice if it exited the current menu, e.g. exiting the Point Impulse menu, ruler, etc.

**Comment by KyroVibe** [comment]
Hi TrevCan. Thank you for the advice. We'll make sure to keep this in mind with the next update.

**Comment by HiceS** [comment]
This is actually some really good feedback, good idea. Let's leave it open until we actually put it into synthesis. If you already did then go ahead and reclose @KyroVibe .
