### ISSUE TITLE
Stuck on robot code connected.

### ISSUE THREAD

**Issue by Rorybabory2** [Autodesk/synthesis#690]
When trying to run java code on emulator, it says robot code running, but it won't say robot code connected. I've tried wpilib 2020 and 2019 and neither work.

**Comment by KyroVibe** [comment]
Hi @Rorybabory2 , another user had this issue and we found it to be a bug with the current verison of synthesis. You can install version 4.3.2 alternatively. https://github.com/Autodesk/synthesis/releases/tag/v4.3.2

**Comment by Rorybabory** [comment]
Not sure if you can get this, but will this be fixed soon? Its hard for us to use this software when we are tied to an old version of wpilib.
