### ISSUE TITLE
Bug in the 2020 version of the emulator

### ISSUE THREAD

**Issue by Rorybabory** [Autodesk/synthesis#703]
I got a bug on the 2020 version where when trying to run emulator code it gets stuck at robot code running, and never says robot code connected. I swapped to the 2019 version and it worked, however I am wondering what the solution is for 2020, as our team wants to use the newest API.

**Comment by KyroVibe** [comment]
Hi @Rorybabory , we are planning to release an update for kickoff which will include support for 2020 emulation. Currently as it stands it will only support c++ but we are hoping to add java support as well. Once java support is done we'll update to 2021 wpilib

**Comment by matthew17754** [comment]
C++ 2020 support has been implemented and C++ and JAVA support for WPILib 2021 should be released in another week or so.

**Comment by matthew17754** [comment]
@Rorybabory Latest emulation updates have been officially released in [Synthesis4.3.3.2](https://github.com/Autodesk/synthesis/releases/tag/v4.3.3.2). Thanks for your inquiry.
