### ISSUE TITLE
Linked Parts Not Working

### ISSUE THREAD

**Issue by Spaceman113138** [Autodesk/synthesis#827]
### Description
If you use assemblies that are not part of that fusion file when you open the game, it goes crazy and all the parts lie in ground and shake.

### Context
![image](https://media.discordapp.net/attachments/1002446176181833792/1084928796643299378/image.png?width=575&height=470)
![image](https://media.discordapp.net/attachments/1007028102213406920/1097324616717975651/image.png?width=836&height=470)

[Affected Fusion File](https://a360.co/42jy2SX)

**Comment by KyroVibe** [comment]
### Update
Problem lies with Fusions entityTokens and them being reused across design documents. As a result all instanced bodies of similar root parts are added under one root part. This bug is planned for Sprint 1

**Comment by KyroVibe** [comment]
Bug was addressed #831 , will be seen in next release.
