### ISSUE TITLE
More fields for ftc

### ISSUE THREAD

**Issue by arhun0511** [Autodesk/synthesis#856]
It would be better if more fields were added to synthesis, such as ftc fields, instead of focusing on just frc fields.

**Comment by BrandonPacewic** [comment]
We historically have not done this as we only get access to the FRC fields early, so we usually prepare that for release for kickoff each year. I've added this to our backlog so in the future we might have more available.

**Comment by KyroVibe** [comment]
### Update
FTC Fields will be included in Synthesis 6.0.0, expected to release early September

**Comment by arhun0511** [comment]
Thanks for this information, this is great news! Can't wait for the release!
