### ISSUE TITLE
Add-in not working

### ISSUE THREAD

**Issue by kappa95** [Autodesk/synthesis#948]
**Describe the bug**
Installed Synthesis V6 from website but the Add-in does not appear in Inventor Professional 2024 and in Fusion 360 is not opening at all.

from Synthesis log file:

```
2023-10-26 11:16:46,369 - synthesis.import_manager - ERROR - Failed
Traceback (most recent call last):
  File "C:\Users/inse9/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/AddIns/Synthesis\src\general_imports.py", line 36, in <module>
    from proto import deps
  File "C:\Users\inse9\AppData\Roaming\Autodesk\Autodesk Fusion 360\API\AddIns\Synthesis\proto\deps.py", line 3, in <module>
    from os import __file__, path
ImportError: cannot import name '__file__' from 'os' (unknown location)
```

**Comment by KyroVibe** [comment]
Hello, quick note, we no longer have an Inventor Exporter, however the issue with the Fusion 360 addin is currently being looked into right now.

**Comment by KyroVibe** [comment]
@kappa95 Could you tell me what version of Fusion you are using?

**Comment by kappa95** [comment]
The version of Fusion is: Fusion 360 2.0.17457 x86_64. On OS: Windows 11 Home 22H2 (22621.2428)

**Comment by KyroVibe** [comment]
@kappa95 could you try starting the addin in debug mode. For some reason that seems to fix the issue

**Comment by kappa95** [comment]
It opens VSCode and if I press Run i got the following error:
```shell
Exception has occurred: ImportError
attempted relative import with no known parent package
  File "C:\Users\inse9\AppData\Roaming\Autodesk\Autodesk Fusion 360\API\AddIns\Synthesis\Synthesis.py", line 1, in <module>
    from .src.general_imports import root_logger, gm, INTERNAL_ID, APP_NAME, DESCRIPTION
ImportError: attempted relative import with no known parent package
```

**Comment by kappa95** [comment]
I have stopped from Addin. And restarted normally, and now the icon in utilities appears. Probably It was missing a local version of Python (for Autodesk I mean) and then It was needed the requirements i suppose?

**Comment by kappa95** [comment]
Trying to export now I get the following error: ![immagine](https://github.com/Autodesk/synthesis/assets/42738531/22187436-bbf9-4ecf-bc16-ee1e9893f62a)

**Comment by KyroVibe** [comment]
@kappa95 Okidoki, definite progress. From the error messages it looks like one of your joints is corrupted. This can happen depending on a lot of things (most of which are issues with Fusion 360 itself). Considering it looks like you only have 3 joints, I would try to rejoint them and see if that solves it. In the meantime, could you send me a sharelink to your design so I can take a look for myself?

**Comment by kappa95** [comment]
Yes sure! Here it is: https://a360.co/473xMKE

**Comment by kappa95** [comment]
I have tried to save another file and remove old joints and reputting them, but the error is the same.

**Comment by KyroVibe** [comment]
@kappa95 Remove the rigid joint between base and the center point of the environment and instead make the base component grounded. You can do this by right clicking on the component and selecting it in the context menu. The center point resolves to the root component of your scene which has a weird kind of container nature, and thus behaves oddly when trying to create physical relationships with other parts in the design.

**Comment by kappa95** [comment]
It worked!! Thanks! But where is it saved? I don't find any explicit filepath in the code

**Comment by KyroVibe** [comment]
The generated mirabuf file is at `%appdata%/Autodesk/Synthesis/Mira/`. Fields (Static exports) are located in the Fields subdirectory and dynamic files exported with the part flag enabled are located at `%appdata%/Autodesk/Synthesis/MixAndMatch/Mira`
